//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_MeetingMember
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int MeetingId { get; set; }
        public Nullable<int> MemberAs { get; set; }
        public Nullable<bool> IsAttend { get; set; }
    
        public virtual MM_Meeting MM_Meeting { get; set; }
        public virtual MM_User MM_User { get; set; }
    }
}
