//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_MeetingLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MM_MeetingLocation()
        {
            this.MM_Meeting = new HashSet<MM_Meeting>();
        }
    
        public int Id { get; set; }
        public string LocationName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Meeting> MM_Meeting { get; set; }
    }
}
