//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_Meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MM_Meeting()
        {
            this.MM_Agenda = new HashSet<MM_Agenda>();
            this.MM_MeetingMember = new HashSet<MM_MeetingMember>();
            this.MM_Meeting1 = new HashSet<MM_Meeting>();
        }
    
        public int Id { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public int MeetingLocationId { get; set; }
        public int MeetingStatus { get; set; }
        public int CreatedUserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ParentMeetingId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Agenda> MM_Agenda { get; set; }
        public virtual MM_User MM_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_MeetingMember> MM_MeetingMember { get; set; }
        public virtual MM_MeetingLocation MM_MeetingLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MM_Meeting> MM_Meeting1 { get; set; }
        public virtual MM_Meeting MM_Meeting2 { get; set; }
    }
}
