//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Repository.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class entitymmEntities : DbContext
    {
        public entitymmEntities()
            : base("name=MM_P0000001Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MM_Agenda> MM_Agendas { get; set; }
        public virtual DbSet<MM_Meeting> MM_Meetings { get; set; }
        public virtual DbSet<MM_MeetingLocation> MM_MeetingLocations { get; set; }
        public virtual DbSet<MM_MeetingMember> MM_MeetingMembers { get; set; }
        public virtual DbSet<MM_User> MM_Users { get; set; }
        public virtual DbSet<MM_Minute> MM_Minutes { get; set; }
    }
}
